# **Organización de Datos 75.06 - Trabajo Práctico N°1**
P5. Para las películas que duran más de tres horas, ¿cuál es la película con más ROI?

In [1]:
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

peliculas = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/TP1/csv/movies.csv")

Mounted at /content/drive

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [2]:
df_limpio = peliculas[ ['title','runtime','revenue','budget'] ] #Eliminamos columnas innecesarias.
df_limpio = df_limpio[ df_limpio['runtime'] > 180]  #Filtramos por duracion mayor a 3 horas.
df_limpio = df_limpio.loc[~((df_limpio['budget'].astype(int) == 0) | (df_limpio['revenue'].astype(int) == 0))].dropna() #Eliminamos ceros y NaN.
df_limpio['ROI'] = (df_limpio['revenue'] - df_limpio['budget'].astype(int)) / df_limpio['budget'].astype(int) #Calculamos ROI.


df_limpio.loc[[df_limpio['ROI'].idxmax()]] #Buscamos la película com mayor ROI.

                      title  runtime     revenue  budget    ROI
6913  The Birth of a Nation    193.0  11000000.0  100000  109.0